from ..base.constants import authorization_code_flow
from ..base.dev_only import username, user_id

scope = 'playlist-modify-public'
username = username
userid = user_id

spotifyObject = authorization_code_flow(scope, username)

def make_playlist(pl_name="Spotipy Playlist", desc="Generated by Spotipy."):

    """
    :param pl_name: Name for the playlist.
    :param desc: Description for the playlist. (default value doesn't work most of the time)
    :return: URI of the created playlist. (idk why the key is called id, it's the same as the URI)
    """

    spotifyObject.user_playlist_create(
        userid,
        pl_name,
        public=True,
        collaborative=False,
        description=desc)

    return spotifyObject.current_user_playlists()['items'][0]['id']
